examenNFL/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('teams/', include('teams.urls')),
    path('stadium/', include('stadiums.urls')),
    path('cities/', include('cities.urls')),
]

home/urls.py
from django.urls import path
from home import views

app_name = "home"

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('about/', views.About.as_view(), name="about")
]

teams/urls.py
from django.urls import path
from teams import views

app_name = "teams"

urlpatterns = [
    path('list/', views.TeamList.as_view(), name="team_list"),
    path('add/', views.AddTeam.as_view(), name="team_add"),
    path('detail/<int:pk>/', views.DetailTeam.as_view(), name="team_detail"),
    path('update/<int:pk>/', views.UpdateTeam.as_view(), name="team_update"),
    path('delete/<int:pk>/', views.DeleteTeam.as_view(), name="team_delete"),
]

teams/models.py
from django.db import models
from cities.models import Cities
from stadiums.models import Stadiums

CONFERENCE = (
    ('American Football Conference', 'American Football Conference'),
    ('National Football Conference', 'National Football Conference'),
)

# Create your models here.
class TeamStadium(models.Model):
    team = models.ForeignKey('Teams', on_delete=models.CASCADE)
    stadium = models.ForeignKey(Stadiums, on_delete=models.CASCADE)

class Teams(models.Model):
    team_name = models.CharField(max_length=255)
    team_founded = models.IntegerField()
    team_conference = models.CharField(max_length=255, choices=CONFERENCE)
    team_city = models.ForeignKey(Cities, on_delete=models.CASCADE)
    team_stadium = models.ManyToManyField(Stadiums, through='TeamStadium')

    def __str__(self):
        return self.team_name

teams/forms.py
from django import forms
from .models import Teams

class TeamForm(forms.ModelForm):
    class Meta:
        model = Teams
        fields = "__all__"
        widgets = {
            "team_name": forms.TextInput(
                attrs={
                    "type":"text", "class":"form-control", "placeholder":"Insert the name of the stadium"
                }
            ),
            "team_founded": forms.NumberInput(
                attrs={
                    "type":"number", "class":"form-control"
                }
            ),
            "team_conference": forms.Select(
                attrs={
                    "type":"select", "class":"form-control"
                }
            ),
            "team_city": forms.Select(
                attrs={
                    "type":"select", "class":"form-control"
                }
            ),
            "team_stadium": forms.SelectMultiple(
                attrs={
                    "type":"select", "class":"form-control"
                }
            )
        }

class UpdateTeamForm(forms.ModelForm):
    class Meta:
        model = Teams
        fields = "__all__"
        widgets = {
            "team_name": forms.TextInput(
                attrs={
                    "type":"text", "class":"form-control", "placeholder":"Insert the name of the stadium"
                }
            ),
            "team_founded": forms.NumberInput(
                attrs={
                    "type":"number", "class":"form-control"
                }
            ),
            "team_conference": forms.Select(
                attrs={
                    "type":"select", "class":"form-control"
                }
            ),
            "team_city": forms.Select(
                attrs={
                    "type":"select", "class":"form-control"
                }
            ),
            "team_stadium": forms.SelectMultiple(
                attrs={
                    "type":"select", "class":"form-control"
                }
            )
        }

teams/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from .models import Teams
from .forms import TeamForm, UpdateTeamForm



# Create your views here.
#Create
class AddTeam(generic.CreateView):
    template_name = "teams/team_create.html"
    model = Teams
    form_class = TeamForm
    success_url = reverse_lazy("teams:team_list")

#List
class TeamList(generic.View):
    template_name = "teams/team_list.html"
    context = {}

    def get(self, request, *args, **kwargs):
        teams_list = Teams.objects.all()
        self.context = {
            "teams": teams_list
        }

        return render(request, self.template_name, self.context)

#Details
class DetailTeam(generic.DetailView):
    template_name = "teams/team_detail.html"
    model = Teams

#Update
class UpdateTeam(generic.UpdateView):
    template_name = "teams/team_update.html"
    model = Teams
    form_class = UpdateTeamForm
    success_url = reverse_lazy("teams:team_list")

#Delete
class DeleteTeam(generic.DeleteView):
    template_name = "teams/team_delete.html"
    model = Teams
    success_url = reverse_lazy("teams:team_list")

templates/teams/team_create.html
{% extends "base/base.html" %}

{% block title %}
Add Teams
{% endblock title %}

{% block content %}
<br>
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-success">Add Team</button>
        <a href="{% url 'teams:team_list' %}" class="btn btn-primary">Cancel</a>
    </form>
<br>
{% endblock content %}

templates/teams/team_delete.html
{% extends "base/base.html" %}

{% block title %}
Delete Team
{% endblock title %}

{% block content %}
<br>
    <form action="" method="post">
        {% csrf_token %}
        ¿Wish you delete: {{ object }}?
        <button type="submit" class="btn btn-primary">Delete Team</button>
        <a href="{% url 'teams:team_list'%}" class="btn btn-warning">Cancel</a>
    </form>
<br>
{% endblock content %}

templates/teams/team_detail.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}
Details Teams
{% endblock title %}

{% block content %}
<br>
<div class="row">
  <div class="col">
    <a href="{% url 'teams:team_list' %}" class="btn btn-success d-grid">BACK TO TEAMS</a>
  </div>
</div>
<br>
<div class="row">
  <div class="col">
    <div class="card bg-dark text-white">
        <img src="{% static 'img/cities/city.jpg' %}" class="card-img" alt="...">
        <div class="card-img-overlay">
          <h5 class="card-title">{{ object.team_name }}</h5>
        </div>
      </div>
  </div>
</div>
<br>
{% endblock content %}

templates/teams/team_list.html
{% extends "base/base.html" %}

{% block title %}
Teams
{% endblock title %}

{% block content %}
<br>
<div class="row">
  <div class="col-8 d-grid">
    <a href="{% url 'teams:team_add' %}" class="btn btn-success ">ADD TEAM</a>
  </div>
  <div class="col-4 d-grid">
    <a href="{% url 'home:index' %}" class="btn btn-secondary">HOME</a>
  </div>
</div>
<br>
<div class="row">
  <div class="col">
    <table class="table table-hover table-secondary">
      <thead>
        <th>ID</th>
        <th>NAME</th>
        <th>FOUNDED</th>
        <th>CONFERENCE</th>
        <th>CITY</th>
        <th>STADIUM</th>
        <th></th>
        <th>ACTIONS</th>
        <th></th>
      </thead>
      <tbody>
        {% for tm in teams %}
          <tr>
            <td>{{ tm.id }}</td>
            <td>{{ tm.team_name }}</td>
            <td>{{ tm.team_founded }}</td>
            <td>{{ tm.team_conference }}</td>
            <td>{{ tm.team_city }}</td>
            <td>
              {% for stadium in tm.team_stadium.all %}
                    {{ stadium.stadium_name }}
                    {% if not forloop.last %}, {% endif %}
                {% endfor %}
            </td>
            <td><a href="{% url 'teams:team_detail' tm.id %}" class="btn btn-info">Details</a></td>
            <td><a href="{% url 'teams:team_update' tm.id %}" class="btn btn-warning">Update</a></td>
            <td><a href="{% url 'teams:team_delete' tm.id %}" class="btn btn-primary">Delete</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<br>
{% endblock content %}

templates/teams/team_update.html
{% extends "base/base.html" %}

{% block title %}
Update Team
{% endblock title %}

{% block content %}
<br>
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-info">Update Team</button>
        <a href="{% url 'teams:team_list' %}" class="btn btn-primary">Cancel</a>
    </form>
<br>
{% endblock content %}