cities/urls.py
from django.urls import path
from cities import views

app_name = "cities"

urlpatterns = [
    path('list/', views.ListCities.as_view(), name="city_list"),
    path('add/', views.AddCity.as_view(), name="city_add"),
    path('detail/<int:pk>/', views.DetailCity.as_view(), name="city_detail"),
    path('update/<int:pk>/', views.UpdateCity.as_view(), name="city_update"),
    path('delete/<int:pk>/', views.DeleteCity.as_view(), name="city_delete"),
]

examenNFL/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('teams/', include('teams.urls')),
    path('stadium/', include('stadiums.urls')),
    path('cities/', include('cities.urls')),
]

home/urls.py
from django.urls import path
from home import views

app_name = "home"

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('about/', views.About.as_view(), name="about")
]

stadiums/urls.py
from django.urls import path
from stadiums import views

app_name = "stadiums"

urlpatterns = [
    path('list/', views.StadiumList.as_view(), name="stadium_list"),
    path('add/', views.AddStadium.as_view(), name="stadium_add"),
    path('detail/<int:pk>/', views.DetailStadium.as_view(), name="stadium_detail"),
    path('update/<int:pk>/', views.UpdateStadium.as_view(), name="stadium_update"),
    path('delete/<int:pk>/', views.DeleteStadium.as_view(), name="stadium_delete"),
]

teams/urls.py
from django.urls import path
from teams import views

app_name = "teams"

urlpatterns = [
    path('list/', views.TeamList.as_view(), name="team_list"),
    path('add/', views.AddTeam.as_view(), name="team_add"),
    path('detail/<int:pk>/', views.DetailTeam.as_view(), name="team_detail"),
    path('update/<int:pk>/', views.UpdateTeam.as_view(), name="team_update"),
    path('delete/<int:pk>/', views.DeleteTeam.as_view(), name="team_delete"),
]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}| Examen</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'img/favicon/site.webmanifest' %}">
</head>
<body>
    <div class="container">
        <header>
            <nav class="navbar navbar-expand-lg" style="background-color: rgba(0, 0, 0, 0.05); border-radius: 10px;" data-bs-theme="dark">
                <div class="container-fluid">
                  <a class="navbar-brand" href="{% url 'home:index' %}"><img src="{% static 'img/NFL_LogoWhite.png' %}" style="width: 25px;"></a>
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                      <li class="nav-item">
                        <a class="nav-link active" href="{% url 'home:index' %}">Home
                          <span class="visually-hidden">(current)</span>
                        </a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:about' %}">About</a>
                      </li>
                      <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Sections</a>
                        <div class="dropdown-menu">
                          <a class="dropdown-item" href="{% url 'teams:team_list' %}">Teams</a>
                          <a class="dropdown-item" href="{% url 'stadiums:stadium_list' %}">Stadiums</a>
                          <a class="dropdown-item" href="{% url 'cities:city_list' %}">Cities</a>
                        </div>
                      </li>
                    </ul>
                  </div>
                </div>
              </nav>
        </header>
        <div class="row">
            <div class="col">
                {% block content %}
                {% endblock content %}
            </div>
        </div>
        <div class="row">
            <div class="col">
                <!-- Footer -->
                <footer class="text-center text-lg-start text-muted">
                    <!-- Copyright -->
                    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05); border-radius: 10px;">
                    © 2023 Copyright:
                    <a class="text-reset fw-bold" href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">AMV24</a>
                    </div>
                    <!-- Copyright -->
                </footer>
                <!-- Footer -->   
            </div>
        </div>
    </div>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>