cities/urls.py
from django.urls import path
from cities import views

app_name = "cities"

urlpatterns = [
    path('list/', views.ListCities.as_view(), name="city_list"),
    path('add/', views.AddCity.as_view(), name="city_add"),
    path('detail/<int:pk>/', views.DetailCity.as_view(), name="city_detail"),
    path('update/<int:pk>/', views.UpdateCity.as_view(), name="city_update"),
    path('delete/<int:pk>/', views.DeleteCity.as_view(), name="city_delete"),
]

examenNFL/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('teams/', include('teams.urls')),
    path('stadium/', include('stadiums.urls')),
    path('cities/', include('cities.urls')),
]

home/urls.py
from django.urls import path
from home import views

app_name = "home"

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('about/', views.About.as_view(), name="about")
]

cities/models.py
from django.db import models

# Create your models here.
class Cities(models.Model):
    city_name = models.CharField(max_length=255)

    def __str__(self):
        return self.city_name

cities/forms.py
from django import forms
from .models import Cities

class CitiesForm(forms.ModelForm):
    class Meta:
        model = Cities
        fields = "__all__"
        widgets = {
            "city_name": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Insert the name of the city"}),
        }

class UpdateCitiesForm(forms.ModelForm):
    class Meta:
        model = Cities
        fields = "__all__"
        widgets = {
            "city_name": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Insert the name of the city"}),
        }

cities/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from .models import Cities
from .forms import CitiesForm, UpdateCitiesForm



# Create your views here.
#Create
class AddCity(generic.CreateView):
    template_name = "cities/city_create.html"
    model = Cities
    form_class = CitiesForm
    success_url = reverse_lazy("cities:city_list")

#List
class ListCities(generic.View):
    template_name = "cities/city_list.html"
    context = {}

    def get(self, request, *args, **kwargs):
        cities_list = Cities.objects.all()
        self.context = {
            "cities": cities_list
        }

        return render(request, self.template_name, self.context)

#Details
class DetailCity(generic.DetailView):
    template_name = "cities/city_detail.html"
    model = Cities

#Update
class UpdateCity(generic.UpdateView):
    template_name = "cities/city_update.html"
    model = Cities
    form_class = UpdateCitiesForm
    success_url = reverse_lazy("cities:city_list")

#Delete
class DeleteCity(generic.DeleteView):
    template_name = "cities/city_delete.html"
    model = Cities
    success_url = reverse_lazy("cities:city_list")

templates/cities/city_create.html
{% extends "base/base.html" %}

{% block title %}
City Cities
{% endblock title %}

{% block content %}
<br>
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-success">Add City</button>
        <a href="{% url 'cities:city_list' %}" class="btn btn-primary">Cancel</a>
    </form>
<br>
{% endblock content %}

templates/cities/city_delete.html
{% extends "base/base.html" %}

{% block title %}
Delete Cities
{% endblock title %}

{% block content %}
<br>
    <form action="" method="post">
        {% csrf_token %}
        ¿Wish you delete: {{ object }}?
        <button type="submit" class="btn btn-primary">Delete City</button>
        <a href="{% url 'cities:city_list'%}" class="btn btn-warning">Cancel</a>
    </form>
<br>
{% endblock content %}

templates/cities/city_detail.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}
Details City
{% endblock title %}

{% block content %}
<br>
<div class="row">
  <div class="col">
    <a href="{% url 'cities:city_list' %}" class="btn btn-success d-grid">BACK TO CITIES</a>
  </div>
</div>
<br>
<div class="row">
  <div class="col">
    <div class="card bg-dark text-white">
        <img src="{% static 'img/cities/city.jpg' %}" class="card-img" alt="...">
        <div class="card-img-overlay">
          <h5 class="card-title">{{ object.city_name }}</h5>
        </div>
      </div>
  </div>
</div>
<br>
{% endblock content %}

templates/cities/city_list.html
{% extends "base/base.html" %}

{% block title %}
Cities
{% endblock title %}

{% block content %}
<br>
<div class="row">
  <div class="col-8 d-grid">
    <a href="{% url 'cities:city_add' %}" class="btn btn-success ">ADD CITY</a>
  </div>
  <div class="col-4 d-grid">
    <a href="{% url 'home:index' %}" class="btn btn-secondary">HOME</a>
  </div>
</div>
<br>
<div class="row">
  <div class="col">
    <table class="table table-hover table-secondary">
      <thead>
        <th>ID</th>
        <th>NAME</th>
        <th></th>
        <th>ACTIONS</th>
        <th></th>
      </thead>
      <tbody>
        {% for city in cities %}
          <tr>
            <td>{{ city.id }}</td>
            <td>{{ city.city_name }}</td>
            <td><a href="{% url 'cities:city_detail' city.id %}" class="btn btn-info">Details</a></td>
            <td><a href="{% url 'cities:city_update' city.id %}" class="btn btn-warning">Update</a></td>
            <td><a href="{% url 'cities:city_delete' city.id %}" class="btn btn-primary">Delete</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<br>
{% endblock content %}

templates/cities/city_update.html
{% extends "base/base.html" %}

{% block title %}
Update Cities
{% endblock title %}

{% block content %}
<br>
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-info">Update City</button>
        <a href="{% url 'cities:city_list' %}" class="btn btn-primary">Cancel</a>
    </form>
<br>
{% endblock content %}