examenNFL/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('teams/', include('teams.urls')),
    path('stadium/', include('stadiums.urls')),
    path('cities/', include('cities.urls')),
]

home/urls.py
from django.urls import path
from home import views

app_name = "home"

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('about/', views.About.as_view(), name="about")
]

stadiums/urls.py
from django.urls import path
from stadiums import views

app_name = "stadiums"

urlpatterns = [
    path('list/', views.StadiumList.as_view(), name="stadium_list"),
    path('add/', views.AddStadium.as_view(), name="stadium_add"),
    path('detail/<int:pk>/', views.DetailStadium.as_view(), name="stadium_detail"),
    path('update/<int:pk>/', views.UpdateStadium.as_view(), name="stadium_update"),
    path('delete/<int:pk>/', views.DeleteStadium.as_view(), name="stadium_delete"),
]

stadiums/models.py
from django.db import models
from cities.models import Cities

# Create your models here.
class Stadiums(models.Model):
    stadium_name = models.CharField(max_length=255)
    stadium_capacity = models.IntegerField()
    stadium_city = models.ForeignKey(Cities, on_delete=models.CASCADE)

    def __str__(self):
        return self.stadium_name

stadiums/forms.py
from django import forms
from .models import Stadiums

class StadiumForm(forms.ModelForm):
    class Meta:
        model = Stadiums
        fields = "__all__"
        widgets = {
            "stadium_name": forms.TextInput(
                attrs={
                    "type":"text", "class":"form-control", "placeholder":"Insert the name of the stadium"
                }
            ),
            "stadium_capacity": forms.NumberInput(
                attrs={
                    "type":"number", "class":"form-control"
                }
            ),
            "stadium_city": forms.Select(
                attrs={
                    "type":"select", "class":"form-control"
                }
            )
        }

class UpdateStadiumForm(forms.ModelForm):
    class Meta:
        model = Stadiums
        fields = "__all__"
        widgets = {
            "stadium_name": forms.TextInput(
                attrs={
                    "type":"text", "class":"form-control", "placeholder":"Insert the name of the stadium"
                }
            ),
            "stadium_capacity": forms.NumberInput(
                attrs={
                    "type":"number", "class":"form-control"
                }
            ),
            "stadium_city": forms.Select(
                attrs={
                    "type":"select", "class":"form-control"
                }
            )
        }

stadiums/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from .models import Stadiums
from .forms import StadiumForm, UpdateStadiumForm



# Create your views here.
#Create
class AddStadium(generic.CreateView):
    template_name = "stadiums/stadium_create.html"
    model = Stadiums
    form_class = StadiumForm
    success_url = reverse_lazy("stadiums:stadium_list")

#List
class StadiumList(generic.View):
    template_name = "stadiums/stadium_list.html"
    context = {}

    def get(self, request, *args, **kwargs):
        stadium_list = Stadiums.objects.all()
        self.context = {
            "stadium": stadium_list
        }

        return render(request, self.template_name, self.context)

#Details
class DetailStadium(generic.DetailView):
    template_name = "stadiums/stadium_detail.html"
    model = Stadiums

#Update
class UpdateStadium(generic.UpdateView):
    template_name = "stadiums/stadium_update.html"
    model = Stadiums
    form_class = UpdateStadiumForm
    success_url = reverse_lazy("stadiums:stadium_list")

#Delete
class DeleteStadium(generic.DeleteView):
    template_name = "stadiums/stadium_delete.html"
    model = Stadiums
    success_url = reverse_lazy("stadiums:stadiums_list")

templates/stadiums/stadium_create.html
{% extends "base/base.html" %}

{% block title %}
Add Stadiums
{% endblock title %}

{% block content %}
<br>
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-success">Add Stadium</button>
        <a href="{% url 'stadiums:stadium_list' %}" class="btn btn-primary">Cancel</a>
    </form>
<br>
{% endblock content %}

templates/stadiums/stadium_delete.html
{% extends "base/base.html" %}

{% block title %}
Delete Stadiums
{% endblock title %}

{% block content %}
<br>
    <form action="" method="post">
        {% csrf_token %}
        ¿Wish you delete: {{ object }}?
        <button type="submit" class="btn btn-primary">Delete Stadium</button>
        <a href="{% url 'stadiums:stadium_list'%}" class="btn btn-warning">Cancel</a>
    </form>
<br>
{% endblock content %}

templates/stadiums/stadium_detail.html
{% extends "base/base.html" %}
{% load static %}
{% load humanize %}

{% block title %}
Details Stadium
{% endblock title %}

{% block content %}
<br>
<div class="row">
  <div class="col">
    <a href="{% url 'stadiums:stadium_list' %}" class="btn btn-success d-grid">BACK TO STADIUMS</a>
  </div>
</div>
<br>
<div class="row">
  <div class="col">
    <div class="card bg-dark text-white">
        <img src="{% static 'img/cities/city.jpg' %}" class="card-img" alt="...">
        <div class="card-img-overlay">
          <h5 class="card-title">{{ object.stadium_name }} | {{ object.stadium_capacity|intcomma }}</h5>
          <p class="card-text">{{ object.stadium_city }}</p>
          <p class="card-text"></p>
        </div>
      </div>
  </div>
</div>
<br>
{% endblock content %}

templates/stadiums/stadium_list.html
{% extends "base/base.html" %}

{% block title %}
Stadiums
{% endblock title %}

{% block content %}
<br>
<div class="row">
  <div class="col-8 d-grid">
    <a href="{% url 'stadiums:stadium_add' %}" class="btn btn-success ">ADD STADIUM</a>
  </div>
  <div class="col-4 d-grid">
    <a href="{% url 'home:index' %}" class="btn btn-secondary">HOME</a>
  </div>
</div>
<br>
<div class="row">
  <div class="col">
    <table class="table table-hover table-secondary">
      <thead>
        <th>ID</th>
        <th>NAME</th>
        <th>CAPACITY</th>
        <th>CITY</th>
        <th></th>
        <th>ACTIONS</th>
        <th></th>
      </thead>
      <tbody>
        {% for st in stadium %}
          <tr>
            <td>{{ st.id }}</td>
            <td>{{ st.stadium_name }}</td>
            <td>{{ st.stadium_capacity }}</td>
            <td>{{ st.stadium_city }}</td>
            <td><a href="{% url 'stadiums:stadium_detail' st.id %}" class="btn btn-info">Details</a></td>
            <td><a href="{% url 'stadiums:stadium_update' st.id %}" class="btn btn-warning">Update</a></td>
            <td><a href="{% url 'stadiums:stadium_delete' st.id %}" class="btn btn-primary">Delete</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<br>
{% endblock content %}

templates/stadiums/stadium_update.html
{% extends "base/base.html" %}

{% block title %}
Update Stadium
{% endblock title %}

{% block content %}
<br>
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-info">Update Stadium</button>
        <a href="{% url 'stadiums:stadium_list' %}" class="btn btn-primary">Cancel</a>
    </form>
<br>
{% endblock content %}